services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      - laravel_app
    networks:
      - laravel
    profiles: ["dev"]

  laravel_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    profiles: ["dev"]
    depends_on:
      mysql:
        condition: service_healthy

  laravel_self:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: self
    container_name: laravel_self
    ports:
      - "8080:9000"
    networks:
      - laravel
    profiles: ["self"]
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    # if we want bundle my.cnf into image
    #build:
    #  context: docker/mysql
    #  dockerfile: Dockerfile
    image: mysql:8.4
    container_name: laravel_db
    restart: always
    ports:
      - "30306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      # if not bundled
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my_custom.cnf:ro
    networks:
      - laravel
    profiles: ["dev", "self"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      retries: 5

volumes:
  db_data:

networks:
  laravel:
